version: "3.9"

services:
  customer-api:
    build:
      context: ./Backend/customer-api
    ports:
      - "4000:4000"
    volumes:
      - customer_data:/data/customers

  account-api:
    build:
      context: ./Backend/account-api
    ports:
      - "8081:8081"
    volumes:
      - account_data:/data/accounts


  registration-api:
    build:
      context: ./Backend/registration-api
    ports:
      - "8080:8080"
    volumes:
      - account_data:/data/registration


  # frontend:
  #   build:
  #     context: ./Frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - customer-api
  #     - account-api

volumes:
  customer_data:
  account_data:
  events_data:
